# CONFIGURATION FILE: ADD NETWORK

# live:
  # - name: Polygon Tenderly
    # networks:
      # - name: Mainnet
        # chainid: 137
        # id: polytend
        # host: https://rpc.tenderly.co/fork/5dcac15f-43c1-486f-b000-97b84e74fcbc
        # explorer: https://api.polygonscan.com/api
